services:
  web:
    build: .
    container_name: web_portfolio
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    restart: unless-stopped
